### ISSUE TITLE
Interface pour afficher les tâches du jour

### ISSUE THREAD

**Issue by alarboulletmarin** [alarboulletmarin/todo-list-python#13]
Créer une page ou une interface spécifique pour afficher uniquement les tâches planifiées pour le jour en cours. Cette fonctionnalité aidera les utilisateurs à se concentrer sur les tâches immédiates et à organiser leur journée de manière plus efficace. La liste des tâches du jour doit être mise à jour automatiquement en fonction des dates d'échéance et des rappels définis par l'utilisateur.

**Comment by AndreaLM06** [comment]
La page fonctionne correctement mais maintenant, jai note une erreur sur les dates : maintenant on a `27-03-23` mais on doit avoir `27/03/2023`
